version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mongodb-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ms2fcdswf58q"
s3_prefix = "mongodb-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ProjectName=\"mongoDBTest\" Stage=\"dev\""
image_repositories = []
